In [63]:
import pandas as pd
import numpy as np

In [64]:
df = pd.read_csv("electricity_demand_weather_merged.csv")

In [65]:
df.head()

,datetime,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,wind,india_bheramara_hvdc,india_tripura,india_adani,nepal,remarks,temperature,humidity,rain,windspeed
0,2020-01-01 00:00:00,5913.0,5913,0,5493,0,160,47,0.0,NaN,129,76,NaN,NaN,NaN,18.3,74.0,0.0,3.5
1,2020-01-01 01:00:00,5570.0,5570,0,5117,0,160,47,0.0,NaN,129,74,NaN,NaN,NaN,16.5,81.0,0.0,6.0
2,2020-01-01 02:00:00,5351.0,5351,0,4900,0,159,47,0.0,NaN,129,72,NaN,NaN,NaN,14.6,89.0,0.0,8.4
3,2020-01-01 03:00:00,5223.0,5223,0,4773,0,160,46,0.0,NaN,129,70,NaN,NaN,NaN,14.5,90.0,0.0,6.3
4,2020-01-01 04:00:00,5142.0,5142,0,4697,0,159,46,0.0,NaN,129,68,NaN,NaN,NaN,14.1,90.0,0.0,8.2

In [66]:
df=df.rename(columns={
    'generation_mw': 'total_generation_mw',
    'demand_mw': 'demand_mw',
    'load_shedding': 'load_shedding_mw',
    'gas': 'gen_gas_mw',
    'liquid_fuel': 'gen_liquid_fuel_mw',
    'coal': 'gen_coal_mw',
    'hydro': 'gen_hydro_mw',
    'solar': 'gen_solar_mw',
    'wind': 'gen_wind_mw',
    'india_bheramara_hvdc': 'import_india_bheramara_mw',
    'india_tripura': 'import_india_tripura_mw',
    'india_adani': 'import_india_adani_mw',
    'nepal': 'import_nepal_mw',
    'temperature': 'temp_c',
    'humidity': 'humidity_pct',
    'rain': 'rain_mm',
    'windspeed': 'wind_speed_ms'
})

In [67]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [68]:
df = df.set_index("datetime")

In [69]:
df.isna().sum()

total_generation_mw              0
demand_mw                        0
load_shedding_mw                 0
gen_gas_mw                       0
gen_liquid_fuel_mw               0
gen_coal_mw                      0
gen_hydro_mw                     0
gen_solar_mw                     0
gen_wind_mw                  31188
import_india_bheramara_mw        0
import_india_tripura_mw          0
import_india_adani_mw        42526
import_nepal_mw              44513
remarks                      46058
temp_c                        1991
humidity_pct                  1991
rain_mm                       1991
wind_speed_ms                 1991
dtype: int64

In [70]:
df.sample(5)

,total_generation_mw,demand_mw,load_shedding_mw,gen_gas_mw,gen_liquid_fuel_mw,gen_coal_mw,gen_hydro_mw,gen_solar_mw,gen_wind_mw,import_india_bheramara_mw,import_india_tripura_mw,import_india_adani_mw,import_nepal_mw,remarks,temp_c,humidity_pct,rain_mm,wind_speed_ms
datetime,,,,,,,,,,,,,,,,,,
2022-12-10 10:00:00,7467.0,7467,0,4551,919,883,46,255.0,NaN,764,64,NaN,NaN,NaN,23.2,65.0,0.0,7.9
2024-08-29 07:00:00,11668.0,11970,288,4891,1129,3490,214,220.0,0.0,895,74,755.0,NaN,NaN,27.1,90.0,0.0,5.0
2021-04-30 01:00:00,11908.0,11908,0,6514,3546,754,35,0.0,NaN,933,142,NaN,NaN,NaN,28.5,64.0,0.0,9.1
2022-04-19 05:00:00,10870.0,10870,0,6291,3137,325,63,2.0,NaN,939,128,NaN,NaN,NaN,25.2,97.0,0.0,9.7
2021-08-09 22:00:00,12399.0,12399,0,6619,4117,716,122,0.0,NaN,698,140,NaN,NaN,NaN,28.1,89.0,0.0,11.9

In [71]:
df = df.drop(columns=['gen_wind_mw'])

In [72]:
df.isna().sum()

total_generation_mw              0
demand_mw                        0
load_shedding_mw                 0
gen_gas_mw                       0
gen_liquid_fuel_mw               0
gen_coal_mw                      0
gen_hydro_mw                     0
gen_solar_mw                     0
import_india_bheramara_mw        0
import_india_tripura_mw          0
import_india_adani_mw        42526
import_nepal_mw              44513
remarks                      46058
temp_c                        1991
humidity_pct                  1991
rain_mm                       1991
wind_speed_ms                 1991
dtype: int64